owner: globetrotter-finance
repo: saras-status

sites:
  - name: "--- WEB APPLICATIONS ---"
    url: https://group1.invalid
  - name: Saras Web App
    url: https://app.sarasfinance.com
  - name: Saras Admin App
    url: https://admin.sarasfinance.com
  
  - name: "--- PRODUCTION SERVERS ---"
    url: https://group2.invalid
  - name: Production Backend Services Health
    url: https://ind-prod.sarasfinance.com/health

  - name: "--- D SERVERS ---"
    url: https://group3.invalid
  - name: Internal Dev Derver
    url: https://ind-dev.sarasfinance.com/health

status-website:
  cname: statuschecks.sarasfinance.com
  logoUrl: https://app.sarasfinance.com/img/logo-with-title.0c272aaa.svg
  name: Saras Status Page
  navbar:
    - title: Status
      href: /
    - title: "Contact Support"
      href: mailto:support@sarasfinance.com

  customCSS: |
    :root {
      --bg-color: #fcfdfe;
      --text-color: #1a1a1a;
      --primary-color: #1a4f76;
      --success-color: #00b894;
      --error-color: #e74c3c;
      --warning-color: #f1c40f;
    }

    /* Hide Footer and Branding */
    footer { display: none !important; }
    .powered-by { display: none !important; }

    /* Optional: Remove the "GitHub" link in the intro text */
    .intro a { color: var(--primary-color); text-decoration: none; }
    /* Group Header Styling */
    /* This targets any site with "invalid" in the URL */
    [href*="invalid"] {
      pointer-events: none;
      cursor: default;
    }
    [href*="invalid"] .status-dot {
      display: none !important;
    }
    [href*="invalid"] h2, [href*="invalid"] .site-name {
      font-size: 1.1rem;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: #636e72;
      margin-top: 20px;
      border-bottom: 2px solid #dfe6e9;
      padding-bottom: 5px;
    }

workflowSchedule:
  uptime: "*/5 * * * *"        # Checks status (5 mins)
  responseTime: "0 23 * * *"   # Records response times (Default: Daily)
  graphs: "0 0 * * *"          # Generates graphs (Default: Daily)
  staticSite: "0 1 * * *"      # Rebuilds status page (Default: Daily)
