owner: globetrotter-finance
repo: saras-status

sites:
  - name: Saras Web App
    url: https://app.sarasfinance.com
  - name: Saras Admin App
    url: https://admin.sarasfinance.com
  
  - name: Production Backend Services Health
    url: https://ind-prod.sarasfinance.com/health

  - name: Internal Dev Derver
    url: https://ind-dev.sarasfinance.com/health

status-website:
  cname: statuschecks.sarasfinance.com
  logoUrl: https://app.sarasfinance.com/img/logo-with-title.0c272aaa.svg
  name: Saras Status Page
  navbar:
    - title: Status
      href: /
    - title: "Contact Support"
      href: mailto:support@sarasfinance.com

  customCSS: |
    :root {
      --bg-color: #fcfdfe;
      --text-color: #1a1a1a;
      --primary-color: #1a4f76;
      --success-color: #00b894;
      --error-color: #e74c3c;
      --warning-color: #f1c40f;
    }

    /* Hide Footer and Branding */
    footer,
    .powered-by,
    div[class*="powered-by"],
    p[class*="powered-by"] {
      display: none !important;
      visibility: hidden !important;
      height: 0 !important;
      padding: 0 !important;
      margin: 0 !important;
    }
    
    /* Removes the bottom-most text specifically */
    body > footer { 
      display: none !important; 
    }

workflowSchedule:
  uptime: "*/5 * * * *"        # Checks status (5 mins)
  responseTime: "0 23 * * *"   # Records response times (Default: Daily)
  graphs: "0 0 * * *"          # Generates graphs (Default: Daily)
  staticSite: "0 1 * * *"      # Rebuilds status page (Default: Daily)
